### ISSUE TITLE
Sphinx RTD build error

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#291]
Error should be unrelated to recent commits or PRs.

```
Running Sphinx v7.1.2

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/unturned/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 441, in load_extension
    mod = import_module(extname)
  File "/home/docs/.asdf/installs/python/3.8.17/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinx_rtd_theme'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/unturned/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/unturned/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 229, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/unturned/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/unturned/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 444, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx_rtd_theme (exception: No module named 'sphinx_rtd_theme')

Extension error:
Could not import extension sphinx_rtd_theme (exception: No module named 'sphinx_rtd_theme')
```

**Comment by MoltonMontro** [comment]
Tentative fix available in #292.
